spring:
  application:
    name: up-platform-user-service
  datasource:
    url: jdbc:mysql://yanzhenyidai.com:3306/yanzhenyidai?characterEncoding=utf8
    username: root
    password: Baidu@2019
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 1003

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:1001/eureka/

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
feign.hystrix.enabled: true

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

